services:

  backend:
    build: backend
    ports:
      - 8080:80
    volumes:
      - ./backend:/app

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n_data:/home/node/.n8n

  graph:
    image: zepai/graphiti:latest
    ports:
        - "8000:8000"
    
    environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - NEO4J_URI=bolt://neo4j:${NEO4J_PORT}
        - NEO4J_USER=${NEO4J_USER}
        - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j:5.22.0
    
    ports:
        - "7474:7474"  # HTTP
        - "${NEO4J_PORT}:${NEO4J_PORT}"  # Bolt
    volumes:
        - neo4j_data:/data
    environment:
        - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}

volumes:
  neo4j_data:
  n8n_data:
  n8n_shared_files:
