services:

  backend:
    build: backend
    ports:
      - 8080:80
    environment:
      - DB_HOST=psql_backend
      - DB_PORT=5433
      - DB_USER=backend
      - DB_PASSWORD=backend
    volumes:
      - ./backend:/app

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=psql_n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n_data:/home/node/.n8n

  graph:
    image: zepai/graphiti:latest
    ports:
        - "8000:8000"
    
    environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - NEO4J_URI=bolt://neo4j:${NEO4J_PORT}
        - NEO4J_USER=${NEO4J_USER}
        - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j:5.22.0
    
    ports:
        - "7474:7474"  # HTTP
        - "${NEO4J_PORT}:${NEO4J_PORT}"  # Bolt
    volumes:
        - neo4j_data:/data
    environment:
        - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  
  psql_n8n:
    image: postgres
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
    volumes: 
      - psql_n8n:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  psql_backend:
    image: postgres
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
    volumes: 
      - psql_backend:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  neo4j_data:
  n8n_data:
  n8n_shared_files:
  psql_n8n:
  psql_backend: